name: "Pull Request Labeler"
on:
  pull_request:
    branches:
      - main

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Changes in Common Components
    steps:
      - uses: actions/labeler@v4
        bug: 'src/common/**'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
